### ISSUE TITLE
session not starting

### ISSUE THREAD

**Issue by cgogoy08** [MosheBenZacharia/GP-Per-Hour#12]
Start/ end sessions in overlay are greyed out and i cannot scroll on that side of the hub. a cannot get a session to begin. have tried going and coming from multiple banks.

![2023-10-16_16-02-55](https://github.com/MosheBenZacharia/GP-Per-Hour/assets/57886567/2731546d-d4cc-492d-9d14-46c85cdd6f2f)

**Comment by MosheBenZacharia** [comment]
Looks like a session is running. You should see something show up when a profit/loss occurs.

**Comment by MosheBenZacharia** [comment]
That is very strange. Can you send me the logs from your session?

**Comment by cgogoy08** [comment]
where can i find that which you need?

**Comment by cgogoy08** [comment]
[101623logs.txt](https://github.com/MosheBenZacharia/GP-Per-Hour/files/12921725/101623logs.txt)

**Comment by cgogoy08** [comment]
![2023-10-16_17-10-54](https://github.com/MosheBenZacharia/GP-Per-Hour/assets/57886567/b3a847c0-f4c9-4a34-a51d-b42c1df37a90)
![2023-10-16_17-11-57](https://github.com/MosheBenZacharia/GP-Per-Hour/assets/57886567/1a80f4d7-6d3a-4948-a753-b6db6d2450be)

**Comment by MosheBenZacharia** [comment]
can you try right click checking your herb sack?

**Comment by cgogoy08** [comment]
I just left the house unfortunate and I’ll be back about 9pm est, I will
try that upon returning.
Sincerely,
Colton Gogoy

**Comment by cgogoy08** [comment]
ah ha! right clicking and selecting "check" the herb sack corrected it =D thank you so much!

**Comment by MosheBenZacharia** [comment]
Nice, will work on fixing the bug that causes this.

**Comment by MosheBenZacharia** [comment]
will be fixed by https://github.com/runelite/plugin-hub/pull/5089 . will close this when it merges
