### ISSUE TITLE
[Bug] Potted plants counting only as a loss when grown in bank

### ISSUE THREAD

**Issue by HollandeP** [MosheBenZacharia/GP-Per-Hour#27]
Planting a seed inside a pot causes a profit loss event as seeded/watered pots are valueless. If the plant grows into a seedling while in the player's inventory, the value is added back to the session profit. However if the pot is inside the bank and it grows, the value is never added back.

**Comment by MosheBenZacharia** [comment]
Thanks for pointing this out! I will look into a fix.

**Comment by MosheBenZacharia** [comment]
will be fixed by https://github.com/runelite/plugin-hub/pull/5089 . will close this when it merges
