### ISSUE TITLE
[Feature] Only stop session after idle time

### ISSUE THREAD

**Issue by CreativeTechGuy** [MosheBenZacharia/GP-Per-Hour#3]
It seems like this plugin works best for long trips (eg: pvm). It would be great if it didn't always reset every time you opened the bank. If I'm doing any bankstanding activity where I'm constantly opening and closing the bank, the overlay keeps resetting every minute or so which makes it not very useful.

* The concept of a "trip" can be configurable so it doesn't end whenever you open a bank. Maybe provide a few options: bank, idle minutes, manual
* Or make an option so the trip overlay is actually the session stats that are currently in the side panel. Then the trips can be tracked as normal and you'll just end up with hundreds of trips, but you'll get a summary of them in the overlay.

After a little bit of cooking, I had about 50 trips, each with 28 sharks in it. The trips weren't useful but the overall session stats were extremely useful.

Prior art:

* [XP Tracker plugin](https://github.com/runelite/runelite/wiki/XP-Tracker) has XP/hr pause/reset after a configurable number of minutes
* [Bossing Info plugin](https://runelite.net/plugin-hub/show/kph-tracker) has sessions timeout by a configurable number of minutes

Thank you for your consideration! This would make the plugin so much more versatile!

**Comment by MosheBenZacharia** [comment]
This is definitely a good point, since the profit is calculated based on the delta from start to finish its necessary to have them reset whenever any type of bank/grand exchange type UI is open.

I think an option to swap the trip overlay with the session stats seems like the best solution, I can definitely work on adding that!

**Comment by CreativeTechGuy** [comment]
Awesome thank you! Great work.

**Comment by MosheBenZacharia** [comment]
added the ability to show session stats here: https://github.com/MosheBenZacharia/GP-Per-Hour/commit/8c7bca4920b0e1df415b07fcd345c2e97dc86d4c

will close when it merges into plugin hub

**Comment by CreativeTechGuy** [comment]
Ooh exciting! Cannot wait.

**Comment by MosheBenZacharia** [comment]
merged in https://github.com/runelite/plugin-hub/pull/4997 . restart runelite to receive the update :)
