### ISSUE TITLE
[Bug] Pickpocket Vyres doesnt count gems if it goes directly into gem bag

### ISSUE THREAD

**Issue by Stickaplex** [MosheBenZacharia/GP-Per-Hour#30]
Unsure if it happens with other npcs but i assume it does. When pickpocketing vyres it wont add the rubys to current session unless you manually check the gem bag every time. It does show up in chat as well.

**Comment by MosheBenZacharia** [comment]
Hey, thanks for reporting this! Can you screenshot what the message in chat says?

**Comment by Stickaplex** [comment]
https://i.imgur.com/3mANhLr.png here ya go.

**Comment by MosheBenZacharia** [comment]
beautiful, will get a fix in for this soon. thank you!

**Comment by MosheBenZacharia** [comment]
added a potential fix in a PR here: https://github.com/runelite/plugin-hub/pull/5089

I couldn't actually test since my thieving is only 75, so when this merges I would appreciate if you could confirm that it worked!

**Comment by Stickaplex** [comment]
sure thing. when is the merge? or just lmk when it happens

**Comment by MosheBenZacharia** [comment]
Yep, I will let you know. Depends when the runelite team has time to review the changes.

**Comment by MosheBenZacharia** [comment]
it's merged! @Stickaplex

**Comment by Stickaplex** [comment]
Works :) ty @MosheBenZacharia
