### ISSUE TITLE
Rune Pouch Presets Break Tracking

### ISSUE THREAD

**Issue by CreativeTechGuy** [MosheBenZacharia/GP-Per-Hour#35]
As of the update on Feb 21, 2024, Rune Pouches now have a Presets panel which can be viewed in a bank to instantly change out the entire contents of the pouch with another set of runes. When in the bank, if you change presets, the tracker will sometimes think that you just lost all of the runes that were previously in the pouch and just gained all of the new runes you put in the pouch.

The easiest way to reproduce this is to load two totally different pouch presets back to back and it's always reproducible.

It seems like it's not tracking banks correctly since nothing should be tracked as a gain/loss while a bank interface is open.

**Comment by MosheBenZacharia** [comment]
should be fixed in v1.4 when this gets merged: https://github.com/runelite/plugin-hub/pull/5645

**Comment by MosheBenZacharia** [comment]
thanks for reporting this! will close the ticket when the PR gets merged

**Comment by MosheBenZacharia** [comment]
should be fixed now!
