### ISSUE TITLE
Can it track blood fury charges?

### ISSUE THREAD

**Issue by jaredvanvels** [MosheBenZacharia/GP-Per-Hour#4]
This is a really cool plugin! Was trying it at fossil island wyverns and was wondering if you were able to track blood fury charges? Would be cool to see if I'm breaking even when I use blood fury. Thanks for the great plugin

**Comment by MosheBenZacharia** [comment]
Thanks so much, yes I can work on adding that :)

**Comment by MosheBenZacharia** [comment]
added the ability to track blood fury charges here: https://github.com/MosheBenZacharia/GP-Per-Hour/commit/01af6a30f43d207015798a15af89d494f9c0d858

I will close this issue when it merges into plugin hub

**Comment by MosheBenZacharia** [comment]
merged in https://github.com/runelite/plugin-hub/pull/4997 . restart runelite to receive the update :)
