### ISSUE TITLE
[Request for Feature] Add crystal shard value from wiki for gp/hr plugin

### ISSUE THREAD

**Issue by Seiwhiskey** [MosheBenZacharia/GP-Per-Hour#46]
Using the value of converting the shards to dust which are used for making divine super combats.  Currently ~16k each not being tracked.

Fantastic plugin though, thank you so much for making this.

**Comment by MosheBenZacharia** [comment]
this should be possible already, by default there is no value but if you go into the plugin settings there are options to remap the value for crystal shards and dust.
