### ISSUE TITLE
Add support for Toxic Blowpipe ornament kit (Blazing Blowpipe)

### ISSUE THREAD

**Issue by gitguy37** [MosheBenZacharia/GP-Per-Hour#49]
Love your plugin! Hoping you can add support for the Blazing Blowpipe.

Would it just require this change on line 1098 of ChargedWeapon.java?

`.chargedItemIds(12926 /*TOXIC_BLOWPIPE*/, 28688 /*BLAZING_BLOWPIPE*/)`

Blazing Blowpipe (charged) item ID: 28688

https://oldschool.runescape.wiki/w/Blazing_blowpipe#Charged

**Comment by MosheBenZacharia** [comment]
should be fixed when this merges https://github.com/runelite/plugin-hub/pull/6261

**Comment by gitguy37** [comment]
Thanks for the update! Checking the blazing blowpipe after darts have been lost now works to track darts used (based on chat message). The estimated usage based off of attack animation doesn't work as the animation ID is different apparently- blazing blowpipe attack animation ID: 10656

https://github.com/MosheBenZacharia/GP-Per-Hour/blob/946affc6ab4e675ddb9ed2257a5b013de2cfd215/src/main/java/com/gpperhour/weaponcharges/WeaponChargesManager.java#L94

https://github.com/MosheBenZacharia/GP-Per-Hour/blob/946affc6ab4e675ddb9ed2257a5b013de2cfd215/src/main/java/com/gpperhour/weaponcharges/WeaponChargesManager.java#L752-L755

**Comment by MosheBenZacharia** [comment]
oops, forgot to replace that. will work on that soon

**Comment by MosheBenZacharia** [comment]
alright will hopefully work when this merges! https://github.com/runelite/plugin-hub/pull/6311

**Comment by gitguy37** [comment]
Appreciate it! I got curious yesterday and tested those same changes- works great.
