### ISSUE TITLE
Not tracking Venator Bow charges

### ISSUE THREAD

**Issue by jaredvanvels** [MosheBenZacharia/GP-Per-Hour#5]
Not sure if it was just missed or if it's not working correctly but the ancient essence for venator bow charges is not tracked

**Comment by MosheBenZacharia** [comment]
Not currently supported and I don't really have 50m to spare to test it sadly. Btw you can see the list of supported items on the readme here: https://github.com/MosheBenZacharia/GP-Per-Hour#weapons-and-armor-tracking

**Comment by jaredvanvels** [comment]
> Not currently supported and I don't really have 50m to spare to test it sadly. Btw you can see the list of supported items on the readme here: https://github.com/MosheBenZacharia/GP-Per-Hour#weapons-and-armor-tracking

If you have collateral I wouldn't mind lending you a venator bow in game for you to test

**Comment by MosheBenZacharia** [comment]
Hey, I ended up buying one after seeing the price of shards drop, will hope to have this supported soon!

**Comment by MosheBenZacharia** [comment]
will be supported in https://github.com/runelite/plugin-hub/pull/5089 . will close this when it merges
