### ISSUE TITLE
Support for subtracting money for retreival services

### ISSUE THREAD

**Issue by Dogebooch** [MosheBenZacharia/GP-Per-Hour#50]
I love your addon, but I noticed that it doesnt take into account if the player dies, say at Vorkath, where you have to pay 100,000 to retrieve the items. Would be a nice feature to have and I wouldnt imagine too difficult to add

**Comment by MosheBenZacharia** [comment]
Hey, thanks so much. Definitely want to get this added. I do already have an issue here that tracks this request, so I'll close this one: https://github.com/MosheBenZacharia/GP-Per-Hour/issues/17
