### ISSUE TITLE
Group Ironman bank support.

### ISSUE THREAD

**Issue by Shrapnel7** [MosheBenZacharia/GP-Per-Hour#51]
Plugin tracks items taken and given to the group chest as gains/losses, please add support to ignore group ironman bank or add it to normal banking tracking.

**Comment by MosheBenZacharia** [comment]
I actually just started a group ironman so this should be an easy fix! will take a look now

**Comment by MosheBenZacharia** [comment]
ok should be fixed when this merges: https://github.com/runelite/plugin-hub/pull/6510

**Comment by Shrapnel7** [comment]
Wonderful! This will be a nice update, thank you for making this awesome plugin!

**Comment by Shrapnel7** [comment]
Is it normal for a merge to take this long? Sorry if this is a dumb question this is the first time I've posted an issue for a runelite plugin.

**Comment by MosheBenZacharia** [comment]
It's pretty random, sometimes a small update can be merged in under a week, the max it takes is usually a month which is what we're getting close to sadly.

**Comment by MosheBenZacharia** [comment]
its merged :)
